### ISSUE TITLE
Can I contribute to this a bit?

### ISSUE THREAD

**Issue by TheAnachronism** [alphaO4/my-Batch-scripts#1]
I'm the one who asked you on reddit for the repo :D

**Comment by alphaO4** [comment]
Of course man feel free to contribute and modify

**Comment by alphaO4** [comment]
> I'm the one who asked you on reddit for the repo :D

Nice 👍

**Comment by alphaO4** [comment]
Sorry I just realised that I have to add you, my bad I apologise
